### pandas practice set 1 continued

In [90]:
import pandas as pd

importCreate two Series:

s1 = [1,2,3,4,5]
s2 = [10,20,30,40,50]

Perform:

addition
subtraction
multiplication
division

between both Series.

In [91]:
s1=pd.Series([1,2,3,4,5])
s2=pd.Series([10,20,30,40,50])
print(s1+s2)
print(s1-s2)
print(s1*s2)
print(s1/s2)

0    11
1    22
2    33
3    44
4    55
dtype: int64
0    -9
1   -18
2   -27
3   -36
4   -45
dtype: int64
0     10
1     40
2     90
3    160
4    250
dtype: int64
0    0.1
1    0.1
2    0.1
3    0.1
4    0.1
dtype: float64

8.

Create a Series:

[12, 45, 67, 23, 89, 90, 34]

Filter and display:

values greater than 50
values less than 30

In [92]:
s1=pd.Series([12,45,67,23,89,90,34])
values=s1[(s1>50)]
print(values)
value2=s1[s1<30]
print(value2)

2    67
4    89
5    90
dtype: int64
0    12
3    23
dtype: int64

9.

Create a Series:

[2,4,6,8,10]

Convert it into a NumPy array and print:

converted array
datatype of converted object

In [93]:
s = pd.Series([2,4,6,8,10])

arr = s.to_numpy()

print(arr)
print(type(arr))

[ 2  4  6  8 10]
<class 'numpy.ndarray'>

10.

Create a Series:

[1,2,2,3,4,4,5,6,6]

Find:

unique values
number of unique values

In [94]:
s=pd.Series([1,2,2,3,4,4,5,6,6])
print(s.unique())
print(s.nunique())

[1 2 3 4 5 6]
6

11.Create a DataFrame using:

{
 "Name": ["Aman","Riya","Karan"],
 "Age": [21,22,20],
 "Marks": [85,90,78]
}
Print the DataFrame.

In [95]:
data=pd.DataFrame({"Name":['Aman','Riya','Karan'],
                   "age":[21,22,20],
                   "Marks":[85,90,78]})
print(data)

    Name  age  Marks
0   Aman   21     85
1   Riya   22     90
2  Karan   20     78

12.

Create a DataFrame from:

[
 [101,"Laptop",55000],
 [102,"Phone",30000],
 [103,"Tablet",25000]
]

Use column names:

Product_ID
Product_Name
Price

In [96]:
data=pd.DataFrame({"ProductID":[101,102,103],
                   "Product_Name":["laptop",'Phone','Tablet'],
                   "Price":[55000,30000,25000]})
print(data) # my method 

# other method better appraoch

data_1=pd.DataFrame([[101, "Laptop", 55000],
        [102, "Phone", 30000],
        [103, "Tablet", 25000]],columns=["Product_ID","Product_Name","Price"])
print(data_1)

   ProductID Product_Name  Price
0        101       laptop  55000
1        102        Phone  30000
2        103       Tablet  25000
   Product_ID Product_Name  Price
0         101       Laptop  55000
1         102        Phone  30000
2         103       Tablet  25000

13.

Create a DataFrame with at least 10 rows containing:

Name
Age
Salary

Display the first 5 rows.

In [97]:
data = pd.DataFrame({
    "Name": ["Aman", "Riya", "Karan", "Neha", "Priya",
             "Rahul", "Sneha", "Arjun", "Pooja", "Vikas"],
    "Age": [21, 22, 20, 23, 24,
            25, 22, 26, 21, 27],
    "Salary": [35000, 42000, 38000, 45000, 50000,
               55000, 40000, 60000, 37000, 65000]
})

data.head(5)

    Name  Age  Salary
0   Aman   21   35000
1   Riya   22   42000
2  Karan   20   38000
3   Neha   23   45000
4  Priya   24   50000

14.

Using the same DataFrame, display the last 5 rows.

In [98]:
data.tail(5)

    Name  Age  Salary
5  Rahul   25   55000
6  Sneha   22   40000
7  Arjun   26   60000
8  Pooja   21   37000
9  Vikas   27   65000

15.

Create a DataFrame containing:

5 rows
4 columns

Find:

total rows
total columns
overall shape

In [99]:
data = pd.DataFrame({
    "Name": ["Aman", "Riya", "Karan", "Neha", "Priya"],
    "Age": [21, 22, 20, 23, 24],
    "Salary": [35000, 42000, 38000, 45000, 50000],
    "Department": ["IT", "HR", "Finance", "Marketing", "IT"]
})

print(data.shape)
print(data.shape[0])
print(data.shape[1])

(5, 4)
5
4

16.

Create an employee DataFrame containing:

Employee_ID
Name
Department
Salary

Display only the column names.

In [100]:
data=pd.DataFrame({"Employee_ID":[1,2,3,4,5],
                   "Name":['Jakc','a','k','fyjik','gio'],
                   "Department":['CS','Marketing','Devops','Docker','sales'],
                   "Salary":[111,634890,5796,6280,690]})
print(data.columns)

Index(['Employee_ID', 'Name', 'Department', 'Salary'], dtype='str')

17.

Create a DataFrame with custom index labels:

["a","b","c","d"]

Print:

DataFrame
index labels

In [101]:
data=pd.DataFrame({"Name": ["Aman", "Riya", "Karan", "Neha", "Priya"],
    "Age": [21, 22, 20, 23, 24],
    "Salary": [35000, 42000, 38000, 45000, 50000],
    "Department": ["IT", "HR", "Finance", "Marketing", "IT"]},index=["a","b","c","d","e"])
print(data)
print(data.index)

    Name  Age  Salary Department
a   Aman   21   35000         IT
b   Riya   22   42000         HR
c  Karan   20   38000    Finance
d   Neha   23   45000  Marketing
e  Priya   24   50000         IT
Index(['a', 'b', 'c', 'd', 'e'], dtype='str')

18.

Create a DataFrame containing:

integer column
float column
string column

Find datatype of every column.

In [102]:
data=pd.DataFrame({"Int":[1,2,3,4],
                   "float":[1.2,223.4,54.5,86.4],
                   "str":["1",'2','3','4']})

print(data.dtypes)

Int        int64
float    float64
str          str
dtype: object

19.

Create a DataFrame of students containing:

Maths marks
Science marks
English marks

Generate summary statistics:

mean
std
min
max
quartiles

In [103]:
marks=pd.DataFrame({"Math":[75,80,53,99,100],
                    "science":[32,76,87,23,65],
                    "English":[65,87,90,32,21]})
marks.describe()

             Math    science   English
count    5.000000   5.000000   5.00000
mean    81.400000  56.600000  59.00000
std     19.398454  27.862161  31.44042
min     53.000000  23.000000  21.00000
25%     75.000000  32.000000  32.00000
50%     80.000000  65.000000  65.00000
75%     99.000000  76.000000  87.00000
max    100.000000  87.000000  90.00000

20.

Create a DataFrame:

Name   Age   Salary

Select and display only:

Name column
Salary column

In [104]:
data=pd.DataFrame({"Name": ["Aman", "Riya", "Karan", "Neha", "Priya"],
    "Age": [21, 22, 20, 23, 24],
    "Salary": [35000, 42000, 38000, 45000, 50000]})

print(data["Name"])
print(data["Salary"])

0     Aman
1     Riya
2    Karan
3     Neha
4    Priya
Name: Name, dtype: str
0    35000
1    42000
2    38000
3    45000
4    50000
Name: Salary, dtype: int64

21.

Using the same DataFrame, select:

Name and Salary together
Age and Salary together

In [105]:
data=pd.DataFrame({"Name": ["Aman", "Riya", "Karan", "Neha", "Priya"],
    "Age": [21, 22, 20, 23, 24],
    "Salary": [35000, 42000, 38000, 45000, 50000]})

print(data[["Name","Salary"]])
print(data[["Age","Salary"]])

    Name  Salary
0   Aman   35000
1   Riya   42000
2  Karan   38000
3   Neha   45000
4  Priya   50000
   Age  Salary
0   21   35000
1   22   42000
2   20   38000
3   23   45000
4   24   50000

22.

Create a DataFrame with 10 rows.

Use loc to:

access a single row
access multiple rows
access rows with specific labels

In [106]:
data = pd.DataFrame({
    "Name": ["Aman", "Riya", "Karan", "Neha", "Priya",
             "Rahul", "Sneha", "Arjun", "Pooja", "Vikas"],
    "Age": [21, 22, 20, 23, 24,
            25, 22, 26, 21, 27],
    "Salary": [35000, 42000, 38000, 45000, 50000,
               55000, 40000, 60000, 37000, 65000]
},
index=["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"])

print(data.loc["c"])
print(data.loc[["b", "d", "f"]])
print(data.loc[["a", "e", "j"]])

Name      Karan
Age          20
Salary    38000
Name: c, dtype: object
    Name  Age  Salary
b   Riya   22   42000
d   Neha   23   45000
f  Rahul   25   55000
    Name  Age  Salary
a   Aman   21   35000
e  Priya   24   50000
j  Vikas   27   65000

23.

Using the same DataFrame, use iloc to:

access first row
access last row
access rows from position 2 to 5

In [107]:
data = pd.DataFrame({
    "Name": ["Aman", "Riya", "Karan", "Neha", "Priya",
             "Rahul", "Sneha", "Arjun", "Pooja", "Vikas"],
    "Age": [21, 22, 20, 23, 24,
            25, 22, 26, 21, 27],
    "Salary": [35000, 42000, 38000, 45000, 50000,
               55000, 40000, 60000, 37000, 65000]
})

print(data.iloc[0])
print(data.iloc[-1])
print(data.iloc[2:6])

Name       Aman
Age          21
Salary    35000
Name: 0, dtype: object
Name      Vikas
Age          27
Salary    65000
Name: 9, dtype: object
    Name  Age  Salary
2  Karan   20   38000
3   Neha   23   45000
4  Priya   24   50000
5  Rahul   25   55000

24.

Create a DataFrame:

Name   Marks   Age

Rename columns into:

Student_Name
Student_Marks
Student_Age

In [108]:
data.rename(columns={
    "Name": "Student_Name",
    "Salary": "Student_Marks",
    "Age": "Student_Age"
}, inplace=True)

print(data.columns)

Index(['Student_Name', 'Student_Age', 'Student_Marks'], dtype='str')