# CODES FROM VIDEO LECS

Installing pandas

In [38]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\tanis\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\tanis\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\tanis\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\tanis\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\tanis\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: C:\Users\tanis\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

importing pandas

In [39]:
import pandas as pd

In [40]:
pd.__version__

'3.0.3'

In [41]:
# 1. create Dataframe
df=pd.DataFrame([11,22,3],columns=['numbers'])
print(df)

   numbers
0       11
1       22
2        3

In [42]:
print(type(df))

<class 'pandas.DataFrame'>

In [43]:
data={
    'Name':['Madhav','Purava','chinki'],
    'Age':[18,22,20],
    'Salary':[10000,200000,3000]
}

In [44]:
df=pd.DataFrame(data)
print(df)

     Name  Age  Salary
0  Madhav   18   10000
1  Purava   22  200000
2  chinki   20    3000

In [45]:
print(type(df))

<class 'pandas.DataFrame'>

### 2. basic dataframe Understanding

In [46]:
df.head(2) # prints top rows

     Name  Age  Salary
0  Madhav   18   10000
1  Purava   22  200000

In [47]:
df.tail(2) # prints bottom 2 rows

     Name  Age  Salary
1  Purava   22  200000
2  chinki   20    3000

In [48]:
df.shape # 3 rows and 3 columns

(3, 3)

In [49]:
df.columns # represents columns

Index(['Name', 'Age', 'Salary'], dtype='str')

In [50]:
df=df.rename(columns={'Salary':"Monthly_salary"})
print(df)
# or we can use inplace method basically it changes in the main column rather than changing temprory

df.rename(columns={'Name':'Employee'},inplace=True)

     Name  Age  Monthly_salary
0  Madhav   18           10000
1  Purava   22          200000
2  chinki   20            3000

In [51]:
df

  Employee  Age  Monthly_salary
0   Madhav   18           10000
1   Purava   22          200000
2   chinki   20            3000

In [52]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Employee        3 non-null      str
 1   Age             3 non-null      int64
 2   Monthly_salary  3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 204.0 bytes

In [53]:
df.describe()

        Age  Monthly_salary
count   3.0        3.000000
mean   20.0    71000.000000
std     2.0   111772.089539
min    18.0     3000.000000
25%    19.0     6500.000000
50%    20.0    10000.000000
75%    21.0   105000.000000
max    22.0   200000.000000

### 3. Save and load data from csv

In [54]:
# lets save the data first 
df.to_csv('Test_data.csv',index=False) #exports data

In [55]:
load_df=pd.read_csv("Test_data.csv")
load_df # imports data

  Employee  Age  Monthly_salary
0   Madhav   18           10000
1   Purava   22          200000
2   chinki   20            3000

In [56]:
df # normal data

  Employee  Age  Monthly_salary
0   Madhav   18           10000
1   Purava   22          200000
2   chinki   20            3000

### 4. Rows and columns- Selection

In [57]:
df[['Employee','Monthly_salary']] #select columns

  Employee  Monthly_salary
0   Madhav           10000
1   Purava          200000
2   chinki            3000

In [58]:
# select rows 
#loc - index name based
df.loc[df.Employee=='Purava'] # for one condition
df.loc[(df.Employee=='Madhav') & (df.Monthly_salary>=100)]
#for mulltiple condition

  Employee  Age  Monthly_salary
0   Madhav   18           10000

In [59]:
#iloc - gives index based values 
df.iloc[0]
df.iloc[0:2] #[start:stop:step]

  Employee  Age  Monthly_salary
0   Madhav   18           10000
1   Purava   22          200000

In [60]:
 # filter the dataframe

df_age=df[(df['Age']>19) & (df['Monthly_salary']>=1000)]

In [61]:
df_age

  Employee  Age  Monthly_salary
1   Purava   22          200000
2   chinki   20            3000

In [62]:
# where method 
df.where(df['Age']>=19, other="Not eligible")

       Employee           Age Monthly_salary
0  Not eligible  Not eligible   Not eligible
1        Purava            22         200000
2        chinki            20           3000

### rows and columns - Operations(add,update,delete)

In [63]:
df

  Employee  Age  Monthly_salary
0   Madhav   18           10000
1   Purava   22          200000
2   chinki   20            3000

In [64]:
# add new column 
df['Team']=['HR','CEO','Tester']
df

  Employee  Age  Monthly_salary    Team
0   Madhav   18           10000      HR
1   Purava   22          200000     CEO
2   chinki   20            3000  Tester

In [65]:
# other method for column 
df['Bonus']=df['Monthly_salary']*0.2
df

  Employee  Age  Monthly_salary    Team    Bonus
0   Madhav   18           10000      HR   2000.0
1   Purava   22          200000     CEO  40000.0
2   chinki   20            3000  Tester    600.0

In [66]:
# add a new row 
df.loc[len(df)]=['piakchu',22,30000,'VIBE CODER',6000]

In [67]:
len(df)

4

In [68]:
# updating the values 
df.loc[0,'Monthly_salary']=50000
df

  Employee  Age  Monthly_salary        Team    Bonus
0   Madhav   18           50000          HR   2000.0
1   Purava   22          200000         CEO  40000.0
2   chinki   20            3000      Tester    600.0
3  piakchu   22           30000  VIBE CODER   6000.0

In [69]:
# other method to update the values 
df.loc[df.Employee=='Madhav','Monthly_Salary']=60000

In [70]:
#deleting values
# deleting rows 
df=df.drop(df[df.Employee=='piakchu'].index)
df

  Employee  Age  Monthly_salary    Team    Bonus  Monthly_Salary
0   Madhav   18           50000      HR   2000.0         60000.0
1   Purava   22          200000     CEO  40000.0             NaN
2   chinki   20            3000  Tester    600.0             NaN

In [71]:
# deleting columns 
df=df.drop('Monthly_Salary',axis=1)

In [72]:
df

  Employee  Age  Monthly_salary    Team    Bonus
0   Madhav   18           50000      HR   2000.0
1   Purava   22          200000     CEO  40000.0
2   chinki   20            3000  Tester    600.0

In [73]:
# sorting of the values
df.sort_values('Monthly_salary',ascending=False)

  Employee  Age  Monthly_salary    Team    Bonus
1   Purava   22          200000     CEO  40000.0
0   Madhav   18           50000      HR   2000.0
2   chinki   20            3000  Tester    600.0

### WORKING WITH DATE VALUES