# CODES FROM VIDEO LECS

Installing pandas

In [119]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\tanis\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\tanis\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\tanis\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\tanis\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\tanis\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: C:\Users\tanis\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

importing pandas

In [120]:
import pandas as pd

In [121]:
pd.__version__

'3.0.3'

In [122]:
# 1. create Dataframe
df=pd.DataFrame([11,22,3],columns=['numbers'])
print(df)

   numbers
0       11
1       22
2        3

In [123]:
print(type(df))

<class 'pandas.DataFrame'>

In [124]:
data={
    'Name':['Madhav','Purava','chinki'],
    'Age':[18,22,20],
    'Salary':[10000,200000,3000]
}

In [125]:
df=pd.DataFrame(data)
print(df)

     Name  Age  Salary
0  Madhav   18   10000
1  Purava   22  200000
2  chinki   20    3000

In [126]:
print(type(df))

<class 'pandas.DataFrame'>

### 2. basic dataframe Understanding

In [127]:
df.head(2) # prints top rows

     Name  Age  Salary
0  Madhav   18   10000
1  Purava   22  200000

In [128]:
df.tail(2) # prints bottom 2 rows

     Name  Age  Salary
1  Purava   22  200000
2  chinki   20    3000

In [129]:
df.shape # 3 rows and 3 columns

(3, 3)

In [130]:
df.columns # represents columns

Index(['Name', 'Age', 'Salary'], dtype='str')

In [131]:
df=df.rename(columns={'Salary':"Monthly_salary"})
print(df)
# or we can use inplace method basically it changes in the main column rather than changing temprory

df.rename(columns={'Name':'Employee'},inplace=True)

     Name  Age  Monthly_salary
0  Madhav   18           10000
1  Purava   22          200000
2  chinki   20            3000

In [132]:
df

  Employee  Age  Monthly_salary
0   Madhav   18           10000
1   Purava   22          200000
2   chinki   20            3000

In [133]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Employee        3 non-null      str
 1   Age             3 non-null      int64
 2   Monthly_salary  3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 204.0 bytes

In [134]:
df.describe()

        Age  Monthly_salary
count   3.0        3.000000
mean   20.0    71000.000000
std     2.0   111772.089539
min    18.0     3000.000000
25%    19.0     6500.000000
50%    20.0    10000.000000
75%    21.0   105000.000000
max    22.0   200000.000000

### 3. Save and load data from csv

In [135]:
# lets save the data first 
df.to_csv('Test_data.csv',index=False) #exports data

In [136]:
load_df=pd.read_csv("Test_data.csv")
load_df # imports data

  Employee  Age  Monthly_salary
0   Madhav   18           10000
1   Purava   22          200000
2   chinki   20            3000

In [137]:
df # normal data

  Employee  Age  Monthly_salary
0   Madhav   18           10000
1   Purava   22          200000
2   chinki   20            3000

### 4. Rows and columns- Selection

In [138]:
df[['Employee','Monthly_salary']] #select columns

  Employee  Monthly_salary
0   Madhav           10000
1   Purava          200000
2   chinki            3000

In [139]:
# select rows 
#loc - index name based
df.loc[df.Employee=='Purava'] # for one condition
df.loc[(df.Employee=='Madhav') & (df.Monthly_salary>=100)]
#for mulltiple condition

  Employee  Age  Monthly_salary
0   Madhav   18           10000

In [140]:
#iloc - gives index based values 
df.iloc[0]
df.iloc[0:2] #[start:stop:step]

  Employee  Age  Monthly_salary
0   Madhav   18           10000
1   Purava   22          200000

In [141]:
 # filter the dataframe

df_age=df[(df['Age']>19) & (df['Monthly_salary']>=1000)]

In [142]:
df_age

  Employee  Age  Monthly_salary
1   Purava   22          200000
2   chinki   20            3000

In [143]:
# where method 
df.where(df['Age']>=19, other="Not eligible")

       Employee           Age Monthly_salary
0  Not eligible  Not eligible   Not eligible
1        Purava            22         200000
2        chinki            20           3000

### rows and columns - Operations(add,update,delete)

In [144]:
df

  Employee  Age  Monthly_salary
0   Madhav   18           10000
1   Purava   22          200000
2   chinki   20            3000

In [145]:
# add new column 
df['Team']=['HR','CEO','Tester']
df

  Employee  Age  Monthly_salary    Team
0   Madhav   18           10000      HR
1   Purava   22          200000     CEO
2   chinki   20            3000  Tester

In [146]:
# other method for column 
df['Bonus']=df['Monthly_salary']*0.2
df

  Employee  Age  Monthly_salary    Team    Bonus
0   Madhav   18           10000      HR   2000.0
1   Purava   22          200000     CEO  40000.0
2   chinki   20            3000  Tester    600.0

In [147]:
# add a new row 
df.loc[len(df)]=['piakchu',22,30000,'VIBE CODER',6000]

In [148]:
len(df)

4

In [149]:
# updating the values 
df.loc[0,'Monthly_salary']=50000
df

  Employee  Age  Monthly_salary        Team    Bonus
0   Madhav   18           50000          HR   2000.0
1   Purava   22          200000         CEO  40000.0
2   chinki   20            3000      Tester    600.0
3  piakchu   22           30000  VIBE CODER   6000.0

In [150]:
# other method to update the values 
df.loc[df.Employee=='Madhav','Monthly_Salary']=60000

In [151]:
#deleting values
# deleting rows 
df=df.drop(df[df.Employee=='piakchu'].index)
df

  Employee  Age  Monthly_salary    Team    Bonus  Monthly_Salary
0   Madhav   18           50000      HR   2000.0         60000.0
1   Purava   22          200000     CEO  40000.0             NaN
2   chinki   20            3000  Tester    600.0             NaN

In [152]:
# deleting columns 
df=df.drop('Monthly_Salary',axis=1)

In [153]:
df

  Employee  Age  Monthly_salary    Team    Bonus
0   Madhav   18           50000      HR   2000.0
1   Purava   22          200000     CEO  40000.0
2   chinki   20            3000  Tester    600.0

In [154]:
# sorting of the values
df.sort_values('Monthly_salary',ascending=False)

  Employee  Age  Monthly_salary    Team    Bonus
1   Purava   22          200000     CEO  40000.0
0   Madhav   18           50000      HR   2000.0
2   chinki   20            3000  Tester    600.0

### WORKING WITH DATE VALUES

In [155]:
df['DOJ']=['2024-01-01','2024-01-15','2024-03-28']
df

  Employee  Age  Monthly_salary    Team    Bonus         DOJ
0   Madhav   18           50000      HR   2000.0  2024-01-01
1   Purava   22          200000     CEO  40000.0  2024-01-15
2   chinki   20            3000  Tester    600.0  2024-03-28

In [156]:
df['DOJ'].dtype

In [157]:
df['DOJ'] = pd.to_datetime(df['DOJ'])

In [158]:
df['DOJ'].dtype

dtype('<M8[us]')

In [159]:
df1 = df

In [160]:
df1

  Employee  Age  Monthly_salary    Team    Bonus        DOJ
0   Madhav   18           50000      HR   2000.0 2024-01-01
1   Purava   22          200000     CEO  40000.0 2024-01-15
2   chinki   20            3000  Tester    600.0 2024-03-28

In [161]:
df1['DOJ2']=['15-01-2025','01-01-2025','28-03-2025']
df1

  Employee  Age  Monthly_salary    Team    Bonus        DOJ        DOJ2
0   Madhav   18           50000      HR   2000.0 2024-01-01  15-01-2025
1   Purava   22          200000     CEO  40000.0 2024-01-15  01-01-2025
2   chinki   20            3000  Tester    600.0 2024-03-28  28-03-2025

In [162]:
df1['DOJ2'].dtype

In [163]:
df1['DOJ2']=pd.to_datetime(df1['DOJ2'],format='%d-%m-%Y')

In [164]:
df1

  Employee  Age  Monthly_salary    Team    Bonus        DOJ       DOJ2
0   Madhav   18           50000      HR   2000.0 2024-01-01 2025-01-15
1   Purava   22          200000     CEO  40000.0 2024-01-15 2025-01-01
2   chinki   20            3000  Tester    600.0 2024-03-28 2025-03-28

In [165]:
df1['DOJ2'].dtype

dtype('<M8[us]')

In [166]:
df.drop('DOJ2',axis=1,inplace=True)
df

  Employee  Age  Monthly_salary    Team    Bonus        DOJ
0   Madhav   18           50000      HR   2000.0 2024-01-01
1   Purava   22          200000     CEO  40000.0 2024-01-15
2   chinki   20            3000  Tester    600.0 2024-03-28

In [167]:
# extract year,month,week,day 
df['DOJ'].dt.year

0    2024
1    2024
2    2024
Name: DOJ, dtype: int32

In [168]:
df['DOJ'].dt.month

0    1
1    1
2    3
Name: DOJ, dtype: int32

In [169]:
df['DOJ'].dt.day

0     1
1    15
2    28
Name: DOJ, dtype: int32

In [170]:
df['DOJ']+pd.Timedelta(days=90)

0   2024-03-31
1   2024-04-14
2   2024-06-26
Name: DOJ, dtype: datetime64[us]

In [171]:
df.isnull()

   Employee    Age  Monthly_salary   Team  Bonus    DOJ
0     False  False           False  False  False  False
1     False  False           False  False  False  False
2     False  False           False  False  False  False

In [172]:
import numpy as np

In [173]:
df.loc[df.Employee=='Madhav','Monthly_salary']=np.nan

In [174]:
df

  Employee  Age  Monthly_salary    Team    Bonus        DOJ
0   Madhav   18             NaN      HR   2000.0 2024-01-01
1   Purava   22        200000.0     CEO  40000.0 2024-01-15
2   chinki   20          3000.0  Tester    600.0 2024-03-28

In [175]:
df.isnull().sum()

Employee          0
Age               0
Monthly_salary    1
Team              0
Bonus             0
DOJ               0
dtype: int64

In [176]:
df.fillna(0)

  Employee  Age  Monthly_salary    Team    Bonus        DOJ
0   Madhav   18             0.0      HR   2000.0 2024-01-01
1   Purava   22        200000.0     CEO  40000.0 2024-01-15
2   chinki   20          3000.0  Tester    600.0 2024-03-28

### 9. aggreate function and group BY

In [177]:
df['Team'].value_counts()

Team
HR        1
CEO       1
Tester    1
Name: count, dtype: int64

In [178]:
df

  Employee  Age  Monthly_salary    Team    Bonus        DOJ
0   Madhav   18             NaN      HR   2000.0 2024-01-01
1   Purava   22        200000.0     CEO  40000.0 2024-01-15
2   chinki   20          3000.0  Tester    600.0 2024-03-28

In [179]:
df.groupby('Age')['Monthly_salary'].sum()

Age
18         0.0
20      3000.0
22    200000.0
Name: Monthly_salary, dtype: float64