In [1]:
import pandas as pd
import numpy as np

# phase 1

In [2]:
df=pd.read_csv("WA_Fn-UseC_-HR-Employee-Attrition.csv")

In [3]:
print(df.head(5))

   Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales
1   49        No  Travel_Frequently        279  Research & Development
2   37       Yes      Travel_Rarely       1373  Research & Development
3   33        No  Travel_Frequently       1392  Research & Development
4   27        No      Travel_Rarely        591  Research & Development

   DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2  Life Sciences              1               1
1                 8          1  Life Sciences              1               2
2                 2          2          Other              1               4
3                 3          4  Life Sciences              1               5
4                 2          1        Medical              1               7

   ...  RelationshipSatisfaction StandardHours  StockOptionLevel  \
0  ...                         1            80                 0
1  ...                         4            80                 1
2  ...                         2            80                 0
3  ...                         3            80                 0
4  ...                         4            80                 1

   TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  YearsAtCompany  \
0                  8                      0               1               6
1                 10                      3               3              10
2                  7                      3               3               0
3                  8                      3               3               8
4                  6                      3               3               2

  YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager
0                  4                        0                     5
1                  7                        1                     7
2                  0                        0                     0
3                  7                        3                     0
4                  2                        2                     2

[5 rows x 35 columns]

In [4]:
df.shape

(1470, 35)

In [5]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='str')

In [6]:
df.dtypes

Age                         int64
Attrition                     str
BusinessTravel                str
DailyRate                   int64
Department                    str
DistanceFromHome            int64
Education                   int64
EducationField                str
EmployeeCount               int64
EmployeeNumber              int64
EnvironmentSatisfaction     int64
Gender                        str
HourlyRate                  int64
JobInvolvement              int64
JobLevel                    int64
JobRole                       str
JobSatisfaction             int64
MaritalStatus                 str
MonthlyIncome               int64
MonthlyRate                 int64
NumCompaniesWorked          int64
Over18                        str
OverTime                      str
PercentSalaryHike           int64
PerformanceRating           int64
RelationshipSatisfaction    int64
StandardHours               int64
StockOptionLevel            int64
TotalWorkingYears           int64
TrainingTimesLastYear       int64
WorkLifeBalance             int64
YearsAtCompany              int64
YearsInCurrentRole          int64
YearsSinceLastPromotion     int64
YearsWithCurrManager        int64
dtype: object

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   str
 2   BusinessTravel            1470 non-null   str
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   str
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   str
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   str
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   str
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   str
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   str
 22  OverTime                  1470 non-null   str
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), str(9)
memory usage: 402.1 KB

In [8]:
df.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,...,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,802.485714,9.192517,2.912925,1.0,1024.865306,2.721769,65.891156,2.729932,2.063946,...,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,403.509100,8.106864,1.024165,0.0,602.024335,1.093082,20.329428,0.711561,1.106940,...,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,491.250000,2.000000,48.000000,2.000000,1.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,802.000000,7.000000,3.000000,1.0,1020.500000,3.000000,66.000000,3.000000,2.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1555.750000,4.000000,83.750000,3.000000,3.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [9]:
df.describe(include=object)

C:\Users\tanis\AppData\Local\Temp\ipykernel_26608\3998025828.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include=object)

,Attrition,BusinessTravel,Department,EducationField,Gender,JobRole,MaritalStatus,Over18,OverTime
count,1470,1470,1470,1470,1470,1470,1470,1470,1470
unique,2,3,3,6,2,9,3,1,2
top,No,Travel_Rarely,Research & Development,Life Sciences,Male,Sales Executive,Married,Y,No
freq,1233,1043,961,606,882,326,673,1470,1054

# Phase 2 (Data Quality Assessment)

In [10]:
print(df.isnull().sum())

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df['EmployeeNumber'].nunique()

1470

In [13]:
df.nunique()

Age                           43
Attrition                      2
BusinessTravel                 3
DailyRate                    886
Department                     3
DistanceFromHome              29
Education                      5
EducationField                 6
EmployeeCount                  1
EmployeeNumber              1470
EnvironmentSatisfaction        4
Gender                         2
HourlyRate                    71
JobInvolvement                 4
JobLevel                       5
JobRole                        9
JobSatisfaction                4
MaritalStatus                  3
MonthlyIncome               1349
MonthlyRate                 1427
NumCompaniesWorked            10
Over18                         1
OverTime                       2
PercentSalaryHike             15
PerformanceRating              2
RelationshipSatisfaction       4
StandardHours                  1
StockOptionLevel               4
TotalWorkingYears             40
TrainingTimesLastYear          7
WorkLifeBalance                4
YearsAtCompany                37
YearsInCurrentRole            19
YearsSinceLastPromotion       16
YearsWithCurrManager          18
dtype: int64

In [14]:
result = (df.isnull().sum() / len(df)) * 100

print(result)

Age                         0.0
Attrition                   0.0
BusinessTravel              0.0
DailyRate                   0.0
Department                  0.0
DistanceFromHome            0.0
Education                   0.0
EducationField              0.0
EmployeeCount               0.0
EmployeeNumber              0.0
EnvironmentSatisfaction     0.0
Gender                      0.0
HourlyRate                  0.0
JobInvolvement              0.0
JobLevel                    0.0
JobRole                     0.0
JobSatisfaction             0.0
MaritalStatus               0.0
MonthlyIncome               0.0
MonthlyRate                 0.0
NumCompaniesWorked          0.0
Over18                      0.0
OverTime                    0.0
PercentSalaryHike           0.0
PerformanceRating           0.0
RelationshipSatisfaction    0.0
StandardHours               0.0
StockOptionLevel            0.0
TotalWorkingYears           0.0
TrainingTimesLastYear       0.0
WorkLifeBalance             0.0
YearsAtCompany              0.0
YearsInCurrentRole          0.0
YearsSinceLastPromotion     0.0
YearsWithCurrManager        0.0
dtype: float64

In [15]:
result = df.nunique()
print(result[result == 1])

EmployeeCount    1
Over18           1
StandardHours    1
dtype: int64

In [16]:
print(df[df["Age"] < 0])
print(df[df["MonthlyIncome"] < 0])
print(df[df["YearsAtCompany"] < 0])
print(df[df["DistanceFromHome"] < 0])
print(df[df["Age"] < 18])

Empty DataFrame
Columns: [Age, Attrition, BusinessTravel, DailyRate, Department, DistanceFromHome, Education, EducationField, EmployeeCount, EmployeeNumber, EnvironmentSatisfaction, Gender, HourlyRate, JobInvolvement, JobLevel, JobRole, JobSatisfaction, MaritalStatus, MonthlyIncome, MonthlyRate, NumCompaniesWorked, Over18, OverTime, PercentSalaryHike, PerformanceRating, RelationshipSatisfaction, StandardHours, StockOptionLevel, TotalWorkingYears, TrainingTimesLastYear, WorkLifeBalance, YearsAtCompany, YearsInCurrentRole, YearsSinceLastPromotion, YearsWithCurrManager]
Index: []

[0 rows x 35 columns]
Empty DataFrame
Columns: [Age, Attrition, BusinessTravel, DailyRate, Department, DistanceFromHome, Education, EducationField, EmployeeCount, EmployeeNumber, EnvironmentSatisfaction, Gender, HourlyRate, JobInvolvement, JobLevel, JobRole, JobSatisfaction, MaritalStatus, MonthlyIncome, MonthlyRate, NumCompaniesWorked, Over18, OverTime, PercentSalaryHike, PerformanceRating, RelationshipSatisfaction, StandardHours, StockOptionLevel, TotalWorkingYears, TrainingTimesLastYear, WorkLifeBalance, YearsAtCompany, YearsInCurrentRole, YearsSinceLastPromotion, YearsWithCurrManager]
Index: []

[0 rows x 35 columns]
Empty DataFrame
Columns: [Age, Attrition, BusinessTravel, DailyRate, Department, DistanceFromHome, Education, EducationField, EmployeeCount, EmployeeNumber, EnvironmentSatisfaction, Gender, HourlyRate, JobInvolvement, JobLevel, JobRole, JobSatisfaction, MaritalStatus, MonthlyIncome, MonthlyRate, NumCompaniesWorked, Over18, OverTime, PercentSalaryHike, PerformanceRating, RelationshipSatisfaction, StandardHours, StockOptionLevel, TotalWorkingYears, TrainingTimesLastYear, WorkLifeBalance, YearsAtCompany, YearsInCurrentRole, YearsSinceLastPromotion, YearsWithCurrManager]
Index: []

[0 rows x 35 columns]
Empty DataFrame
Columns: [Age, Attrition, BusinessTravel, DailyRate, Department, DistanceFromHome, Education, EducationField, EmployeeCount, EmployeeNumber, EnvironmentSatisfaction, Gender, HourlyRate, JobInvolvement, JobLevel, JobRole, JobSatisfaction, MaritalStatus, MonthlyIncome, MonthlyRate, NumCompaniesWorked, Over18, OverTime, PercentSalaryHike, PerformanceRating, RelationshipSatisfaction, StandardHours, StockOptionLevel, TotalWorkingYears, TrainingTimesLastYear, WorkLifeBalance, YearsAtCompany, YearsInCurrentRole, YearsSinceLastPromotion, YearsWithCurrManager]
Index: []

[0 rows x 35 columns]
Empty DataFrame
Columns: [Age, Attrition, BusinessTravel, DailyRate, Department, DistanceFromHome, Education, EducationField, EmployeeCount, EmployeeNumber, EnvironmentSatisfaction, Gender, HourlyRate, JobInvolvement, JobLevel, JobRole, JobSatisfaction, MaritalStatus, MonthlyIncome, MonthlyRate, NumCompaniesWorked, Over18, OverTime, PercentSalaryHike, PerformanceRating, RelationshipSatisfaction, StandardHours, StockOptionLevel, TotalWorkingYears, TrainingTimesLastYear, WorkLifeBalance, YearsAtCompany, YearsInCurrentRole, YearsSinceLastPromotion, YearsWithCurrManager]
Index: []

[0 rows x 35 columns]

In [17]:
df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

# task3

In [18]:
age=df['Age']

In [19]:
print(age.mean())
print(age.median())
# print(age.mode[0])
print(age.min())
print(age.max())
print(age.std())
print(age.var())

36.923809523809524
36.0
18
60
9.135373489136732
83.45504878602223

In [20]:
print(age.quantile(0.25))
print(age.quantile(0.5))
print(age.quantile(0.75))

30.0
36.0
43.0

In [21]:
numerical_columns = [
    "Age",
    "MonthlyIncome",
    "DistanceFromHome",
    "YearsAtCompany",
    "PercentSalaryHike"
]

In [22]:
df[numerical_columns].describe()

,Age,MonthlyIncome,DistanceFromHome,YearsAtCompany,PercentSalaryHike
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,6502.931293,9.192517,7.008163,15.209524
std,9.135373,4707.956783,8.106864,6.126525,3.659938
min,18.000000,1009.000000,1.000000,0.000000,11.000000
25%,30.000000,2911.000000,2.000000,3.000000,12.000000
50%,36.000000,4919.000000,7.000000,5.000000,14.000000
75%,43.000000,8379.000000,14.000000,9.000000,18.000000
max,60.000000,19999.000000,29.000000,40.000000,25.000000

In [23]:
df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

# task 4

In [24]:
workforce =[
    "Department",
    "Gender",
    "JobRole",
    "EducationField",
    "OverTime",
    "MaritalStatus",
    "Attrition"
]

In [25]:
for i in workforce:
    print("\nUnique Categories:")
    print(df[i].nunique())

    print("\nValue Counts:")
    print(df[i].value_counts())

    print("\nPercentage Distribution:")
    print(df[i].value_counts(normalize=True) * 100)

    print("\nMost Common Category:")
    print(df[i].mode()[0])

    print("\nLeast Common Category:")
    print(df[i].value_counts().idxmin())

Unique Categories:
3

Value Counts:
Department
Research & Development    961
Sales                     446
Human Resources            63
Name: count, dtype: int64

Percentage Distribution:
Department
Research & Development    65.374150
Sales                     30.340136
Human Resources            4.285714
Name: proportion, dtype: float64

Most Common Category:
Research & Development

Least Common Category:
Human Resources

Unique Categories:
2

Value Counts:
Gender
Male      882
Female    588
Name: count, dtype: int64

Percentage Distribution:
Gender
Male      60.0
Female    40.0
Name: proportion, dtype: float64

Most Common Category:
Male

Least Common Category:
Female

Unique Categories:
9

Value Counts:
JobRole
Sales Executive              326
Research Scientist           292
Laboratory Technician        259
Manufacturing Director       145
Healthcare Representative    131
Manager                      102
Sales Representative          83
Research Director             80
Human Resources               52
Name: count, dtype: int64

Percentage Distribution:
JobRole
Sales Executive              22.176871
Research Scientist           19.863946
Laboratory Technician        17.619048
Manufacturing Director        9.863946
Healthcare Representative     8.911565
Manager                       6.938776
Sales Representative          5.646259
Research Director             5.442177
Human Resources               3.537415
Name: proportion, dtype: float64

Most Common Category:
Sales Executive

Least Common Category:
Human Resources

Unique Categories:
6

Value Counts:
EducationField
Life Sciences       606
Medical             464
Marketing           159
Technical Degree    132
Other                82
Human Resources      27
Name: count, dtype: int64

Percentage Distribution:
EducationField
Life Sciences       41.224490
Medical             31.564626
Marketing           10.816327
Technical Degree     8.979592
Other                5.578231
Human Resources      1.836735
Name: proportion, dtype: float64

Most Common Category:
Life Sciences

Least Common Category:
Human Resources

Unique Categories:
2

Value Counts:
OverTime
No     1054
Yes     416
Name: count, dtype: int64

Percentage Distribution:
OverTime
No     71.70068
Yes    28.29932
Name: proportion, dtype: float64

Most Common Category:
No

Least Common Category:
Yes

Unique Categories:
3

Value Counts:
MaritalStatus
Married     673
Single      470
Divorced    327
Name: count, dtype: int64

Percentage Distribution:
MaritalStatus
Married     45.782313
Single      31.972789
Divorced    22.244898
Name: proportion, dtype: float64

Most Common Category:
Married

Least Common Category:
Divorced

Unique Categories:
2

Value Counts:
Attrition
No     1233
Yes     237
Name: count, dtype: int64

Percentage Distribution:
Attrition
No     83.877551
Yes    16.122449
Name: proportion, dtype: float64

Most Common Category:
No

Least Common Category:
Yes

# task 5

In [26]:
age=df[df['Age']>40]
print(age)

      Age Attrition     BusinessTravel  DailyRate              Department  \
0      41       Yes      Travel_Rarely       1102                   Sales
1      49        No  Travel_Frequently        279  Research & Development
6      59        No      Travel_Rarely       1324  Research & Development
18     53        No      Travel_Rarely       1219                   Sales
25     53        No      Travel_Rarely       1282  Research & Development
...   ...       ...                ...        ...                     ...
1448   41        No      Travel_Rarely        930                   Sales
1452   50       Yes  Travel_Frequently        878                   Sales
1454   45        No      Travel_Rarely        374                   Sales
1461   50       Yes      Travel_Rarely        410                   Sales
1468   49        No  Travel_Frequently       1023                   Sales

      DistanceFromHome  Education EducationField  EmployeeCount  \
0                    1          2  Life Sciences              1
1                    8          1  Life Sciences              1
6                    3          3        Medical              1
18                   2          4  Life Sciences              1
25                   5          3          Other              1
...                ...        ...            ...            ...
1448                 3          3  Life Sciences              1
1452                 1          4  Life Sciences              1
1454                20          3  Life Sciences              1
1461                28          3      Marketing              1
1468                 2          3        Medical              1

      EmployeeNumber  ...  RelationshipSatisfaction StandardHours  \
0                  1  ...                         1            80
1                  2  ...                         4            80
6                 10  ...                         1            80
18                23  ...                         3            80
25                32  ...                         4            80
...              ...  ...                       ...           ...
1448            2037  ...                         3            80
1452            2044  ...                         4            80
1454            2046  ...                         3            80
1461            2055  ...                         2            80
1468            2065  ...                         4            80

      StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
0                    0                  8                      0
1                    1                 10                      3
6                    3                 12                      3
18                   0                 31                      3
25                   1                 26                      3
...                ...                ...                    ...
1448                 1                 14                      5
1452                 2                 12                      3
1454                 0                  8                      3
1461                 1                 20                      3
1468                 0                 17                      3

     WorkLifeBalance  YearsAtCompany YearsInCurrentRole  \
0                  1               6                  4
1                  3              10                  7
6                  2               1                  0
18                 3              25                  8
25                 2              14                 13
...              ...             ...                ...
1448               3               5                  4
1452               3               6                  3
1454               3               5                  3
1461               3               3                  2
1468               2               9                  6

      YearsSinceLastPromotion  YearsWithCurrManager
0                           0                     5
1                           1                     7
6                           0                     0
18                          3                     7
25                          4                     8
...                       ...                   ...
1448                        0                     4
1452                        0                     1
1454                        0                     1
1461                        2                     0
1468                        0                     8

[465 rows x 35 columns]

In [27]:
high_salary = df[df["MonthlyIncome"] > 10000]

print(high_salary)

      Age Attrition BusinessTravel  DailyRate              Department  \
18     53        No  Travel_Rarely       1219                   Sales
22     34        No  Travel_Rarely        419  Research & Development
25     53        No  Travel_Rarely       1282  Research & Development
28     44        No  Travel_Rarely        477  Research & Development
29     46        No  Travel_Rarely        705                   Sales
...   ...       ...            ...        ...                     ...
1437   39        No     Non-Travel        105  Research & Development
1443   42        No  Travel_Rarely        300  Research & Development
1445   41        No  Travel_Rarely        582  Research & Development
1461   50       Yes  Travel_Rarely        410                   Sales
1462   39        No  Travel_Rarely        722                   Sales

      DistanceFromHome  Education EducationField  EmployeeCount  \
18                   2          4  Life Sciences              1
22                   7          4  Life Sciences              1
25                   5          3          Other              1
28                   7          4        Medical              1
29                   2          4      Marketing              1
...                ...        ...            ...            ...
1437                 9          3  Life Sciences              1
1443                 2          3  Life Sciences              1
1445                28          4  Life Sciences              1
1461                28          3      Marketing              1
1462                24          1      Marketing              1

      EmployeeNumber  ...  RelationshipSatisfaction StandardHours  \
18                23  ...                         3            80
22                28  ...                         3            80
25                32  ...                         4            80
28                36  ...                         4            80
29                38  ...                         4            80
...              ...  ...                       ...           ...
1437            2022  ...                         3            80
1443            2031  ...                         1            80
1445            2034  ...                         3            80
1461            2055  ...                         2            80
1462            2056  ...                         1            80

      StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
18                   0                 31                      3
22                   0                 13                      4
25                   1                 26                      3
28                   1                 24                      4
29                   0                 22                      2
...                ...                ...                    ...
1437                 0                 21                      3
1443                 0                 24                      2
1445                 1                 21                      3
1461                 1                 20                      3
1462                 1                 21                      2

     WorkLifeBalance  YearsAtCompany YearsInCurrentRole  \
18                 3              25                  8
22                 3              12                  6
25                 2              14                 13
28                 3              22                  6
29                 2               2                  2
...              ...             ...                ...
1437               2               6                  0
1443               2              22                  6
1445               3              20                  7
1461               3               3                  2
1462               2              20                  9

      YearsSinceLastPromotion  YearsWithCurrManager
18                          3                     7
22                          2                    11
25                          4                     8
28                          5                    17
29                          2                     1
...                       ...                   ...
1437                        1                     3
1443                        4                    14
1445                        0                    10
1461                        2                     0
1462                        9                     6

[281 rows x 35 columns]

In [28]:
overtime_employees = df[df["OverTime"] == "Yes"]

print(overtime_employees)

      Age Attrition     BusinessTravel  DailyRate              Department  \
0      41       Yes      Travel_Rarely       1102                   Sales
2      37       Yes      Travel_Rarely       1373  Research & Development
3      33        No  Travel_Frequently       1392  Research & Development
6      59        No      Travel_Rarely       1324  Research & Development
11     29        No      Travel_Rarely        153  Research & Development
...   ...       ...                ...        ...                     ...
1450   35        No      Travel_Rarely       1146         Human Resources
1456   35        No  Travel_Frequently       1199  Research & Development
1459   29        No      Travel_Rarely       1378  Research & Development
1461   50       Yes      Travel_Rarely        410                   Sales
1467   27        No      Travel_Rarely        155  Research & Development

      DistanceFromHome  Education EducationField  EmployeeCount  \
0                    1          2  Life Sciences              1
2                    2          2          Other              1
3                    3          4  Life Sciences              1
6                    3          3        Medical              1
11                  15          2  Life Sciences              1
...                ...        ...            ...            ...
1450                26          4  Life Sciences              1
1456                18          4  Life Sciences              1
1459                13          2          Other              1
1461                28          3      Marketing              1
1467                 4          3  Life Sciences              1

      EmployeeNumber  ...  RelationshipSatisfaction StandardHours  \
0                  1  ...                         1            80
2                  4  ...                         2            80
3                  5  ...                         3            80
6                 10  ...                         1            80
11                15  ...                         4            80
...              ...  ...                       ...           ...
1450            2040  ...                         3            80
1456            2049  ...                         4            80
1459            2053  ...                         1            80
1461            2055  ...                         2            80
1467            2064  ...                         2            80

      StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
0                    0                  8                      0
2                    0                  7                      3
3                    0                  8                      3
6                    3                 12                      3
11                   0                 10                      3
...                ...                ...                    ...
1450                 0                  9                      2
1456                 2                 10                      2
1459                 1                 10                      2
1461                 1                 20                      3
1467                 1                  6                      0

     WorkLifeBalance  YearsAtCompany YearsInCurrentRole  \
0                  1               6                  4
2                  3               0                  0
3                  3               8                  7
6                  2               1                  0
11                 3               9                  5
...              ...             ...                ...
1450               3               9                  0
1456               4              10                  2
1459               3               4                  3
1461               3               3                  2
1467               3               6                  2

      YearsSinceLastPromotion  YearsWithCurrManager
0                           0                     5
2                           0                     0
3                           3                     0
6                           0                     0
11                          0                     8
...                       ...                   ...
1450                        1                     7
1456                        0                     2
1459                        0                     3
1461                        2                     0
1467                        0                     3

[416 rows x 35 columns]

In [29]:
sales_department = df[df["Department"] == "Sales"]

print(sales_department)

      Age Attrition     BusinessTravel  DailyRate Department  \
0      41       Yes      Travel_Rarely       1102      Sales
18     53        No      Travel_Rarely       1219      Sales
21     36       Yes      Travel_Rarely       1218      Sales
27     42        No      Travel_Rarely        691      Sales
29     46        No      Travel_Rarely        705      Sales
...   ...       ...                ...        ...        ...
1454   45        No      Travel_Rarely        374      Sales
1461   50       Yes      Travel_Rarely        410      Sales
1462   39        No      Travel_Rarely        722      Sales
1464   26        No      Travel_Rarely       1167      Sales
1468   49        No  Travel_Frequently       1023      Sales

      DistanceFromHome  Education EducationField  EmployeeCount  \
0                    1          2  Life Sciences              1
18                   2          4  Life Sciences              1
21                   9          4  Life Sciences              1
27                   8          4      Marketing              1
29                   2          4      Marketing              1
...                ...        ...            ...            ...
1454                20          3  Life Sciences              1
1461                28          3      Marketing              1
1462                24          1      Marketing              1
1464                 5          3          Other              1
1468                 2          3        Medical              1

      EmployeeNumber  ...  RelationshipSatisfaction StandardHours  \
0                  1  ...                         1            80
18                23  ...                         3            80
21                27  ...                         2            80
27                35  ...                         4            80
29                38  ...                         4            80
...              ...  ...                       ...           ...
1454            2046  ...                         3            80
1461            2055  ...                         2            80
1462            2056  ...                         1            80
1464            2060  ...                         4            80
1468            2065  ...                         4            80

      StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
0                    0                  8                      0
18                   0                 31                      3
21                   0                 10                      4
27                   1                 10                      2
29                   0                 22                      2
...                ...                ...                    ...
1454                 0                  8                      3
1461                 1                 20                      3
1462                 1                 21                      2
1464                 0                  5                      2
1468                 0                 17                      3

     WorkLifeBalance  YearsAtCompany YearsInCurrentRole  \
0                  1               6                  4
18                 3              25                  8
21                 3               5                  3
27                 3               9                  7
29                 2               2                  2
...              ...             ...                ...
1454               3               5                  3
1461               3               3                  2
1462               2              20                  9
1464               3               4                  2
1468               2               9                  6

      YearsSinceLastPromotion  YearsWithCurrManager
0                           0                     5
18                          3                     7
21                          0                     3
27                          4                     2
29                          2                     1
...                       ...                   ...
1454                        0                     1
1461                        2                     0
1462                        9                     6
1464                        0                     0
1468                        0                     8

[446 rows x 35 columns]

In [30]:
female_managers = df[
    (df["Gender"] == "Female") &
    (df["JobRole"] == "Manager")
]

print(female_managers)

      Age Attrition     BusinessTravel  DailyRate              Department  \
18     53        No      Travel_Rarely       1219                   Sales
25     53        No      Travel_Rarely       1282  Research & Development
29     46        No      Travel_Rarely        705                   Sales
65     55        No      Travel_Rarely        836  Research & Development
105    59        No         Non-Travel       1420         Human Resources
112    54        No         Non-Travel        142         Human Resources
116    34        No      Travel_Rarely       1354  Research & Development
165    50        No      Travel_Rarely       1452  Research & Development
186    40        No      Travel_Rarely        989  Research & Development
215    41        No      Travel_Rarely        896                   Sales
233    50        No      Travel_Rarely        854                   Sales
235    43        No      Travel_Rarely       1034                   Sales
263    46        No      Travel_Rarely        488                   Sales
276    35        No      Travel_Rarely       1315  Research & Development
313    33        No  Travel_Frequently        553  Research & Development
352    48        No      Travel_Rarely        530                   Sales
379    55        No      Travel_Rarely       1311  Research & Development
408    52        No      Travel_Rarely       1490  Research & Development
411    60        No      Travel_Rarely        422  Research & Development
417    40        No      Travel_Rarely       1398                   Sales
445    55        No      Travel_Rarely       1117                   Sales
466    41        No      Travel_Rarely       1276                   Sales
492    48        No      Travel_Rarely       1236  Research & Development
592    47        No      Travel_Rarely        202  Research & Development
616    51        No      Travel_Rarely       1318                   Sales
749    52       Yes      Travel_Rarely        266                   Sales
755    45        No      Travel_Rarely       1234                   Sales
851    56        No      Travel_Rarely        718  Research & Development
858    53        No      Travel_Rarely       1223  Research & Development
861    46        No      Travel_Rarely       1402                   Sales
867    50        No  Travel_Frequently       1421  Research & Development
913    45       Yes      Travel_Rarely       1449                   Sales
916    46        No      Travel_Rarely        168                   Sales
936    45        No  Travel_Frequently        364  Research & Development
937    39        No      Travel_Rarely        412  Research & Development
948    30        No      Travel_Rarely        634  Research & Development
955    55        No      Travel_Rarely        282  Research & Development
999    42        No      Travel_Rarely       1147         Human Resources
1076   54        No  Travel_Frequently       1050  Research & Development
1080   46        No      Travel_Rarely        228                   Sales
1154   47        No      Travel_Rarely       1176         Human Resources
1184   54        No      Travel_Rarely        584  Research & Development
1194   47        No      Travel_Rarely       1225                   Sales
1275   51        No      Travel_Rarely        942  Research & Development
1330   43        No      Travel_Rarely        823  Research & Development
1351   48        No  Travel_Frequently        117  Research & Development
1374   58        No      Travel_Rarely        605                   Sales

      DistanceFromHome  Education    EducationField  EmployeeCount  \
18                   2          4     Life Sciences              1
25                   5          3             Other              1
29                   2          4         Marketing              1
65                   8          3           Medical              1
105                  2          4   Human Resources              1
112                 26          3   Human Resources              1
116                  5          3           Medical              1
165                 11          3     Life Sciences              1
186                  4          1           Medical              1
215                  6          3     Life Sciences              1
233                  1          4           Medical              1
235                 16          3         Marketing              1
263                  2          3  Technical Degree              1
276                 22          3     Life Sciences              1
313                  5          4     Life Sciences              1
352                 29          1           Medical              1
379                  2          3     Life Sciences              1
408                  4          2     Life Sciences              1
411                  7          3     Life Sciences              1
417                  2          4     Life Sciences              1
445                 18          5     Life Sciences              1
466                  2          5     Life Sciences              1
492                  1          4     Life Sciences              1
592                  2          2             Other              1
616                 26          4         Marketing              1
749                  2          1         Marketing              1
755                 11          2     Life Sciences              1
851                  4          4  Technical Degree              1
858                  7          2           Medical              1
861                  2          3         Marketing              1
867                  2          3           Medical              1
913                  2          3         Marketing              1
916                  4          2         Marketing              1
936                 25          3           Medical              1
937                 13          4           Medical              1
948                 17          4           Medical              1
955                  2          2           Medical              1
999                 10          3   Human Resources              1
1076                11          4           Medical              1
1080                 3          3     Life Sciences              1
1154                26          4     Life Sciences              1
1184                22          5           Medical              1
1194                 2          4     Life Sciences              1
1275                 3          3  Technical Degree              1
1330                 6          3           Medical              1
1351                22          3           Medical              1
1374                21          3     Life Sciences              1

      EmployeeNumber  ...  RelationshipSatisfaction StandardHours  \
18                23  ...                         3            80
25                32  ...                         4            80
29                38  ...                         4            80
65                84  ...                         3            80
105              140  ...                         4            80
112              148  ...                         3            80
116              153  ...                         4            80
165              226  ...                         2            80
186              253  ...                         2            80
215              298  ...                         3            80
233              323  ...                         3            80
235              327  ...                         3            80
263              363  ...                         2            80
276              381  ...                         2            80
313              428  ...                         2            80
352              473  ...                         2            80
379              505  ...                         3            80
408              546  ...                         4            80
411              549  ...                         4            80
417              558  ...                         4            80
445              597  ...                         4            80
466              625  ...                         2            80
492              664  ...                         1            80
592              820  ...                         3            80
616              851  ...                         3            80
749             1038  ...                         4            80
755             1045  ...                         2            80
851             1191  ...                         4            80
858             1201  ...                         2            80
861             1204  ...                         1            80
867             1215  ...                         3            80
913             1277  ...                         1            80
916             1280  ...                         3            80
936             1306  ...                         3            80
937             1307  ...                         4            80
948             1321  ...                         4            80
955             1336  ...                         4            80
999             1408  ...                         3            80
1076            1520  ...                         1            80
1080            1527  ...                         4            80
1154            1625  ...                         3            80
1184            1665  ...                         3            80
1194            1676  ...                         3            80
1275            1786  ...                         4            80
1330            1866  ...                         4            80
1351            1900  ...                         2            80
1374            1938  ...                         3            80

      StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
18                   0                 31                      3
25                   1                 26                      3
29                   0                 22                      2
65                   3                 21                      2
105                  1                 30                      3
112                  0                 23                      3
116                  0                 14                      6
165                  0                 21                      5
186                  1                 21                      2
215                  0                 16                      3
233                  1                 32                      3
235                  1                 22                      3
263                  1                 28                      2
276                  1                 10                      6
313                  2                 12                      2
352                  1                 15                      3
379                  0                 30                      2
408                  0                 31                      2
411                  0                 33                      5
417                  0                 21                      2
445                  0                 37                      2
466                  1                 22                      2
492                  1                 21                      3
592                  1                 26                      3
616                  1                 29                      2
749                  1                 33                      3
755                  1                 26                      4
851                  1                 28                      2
858                  1                 26                      6
861                  0                 28                      2
867                  1                 32                      3
913                  0                 26                      2
916                  1                 26                      2
936                  0                 22                      4
937                  2                 21                      4
948                  2                  9                      2
955                  1                 23                      5
999                  1                 21                      5
1076                 1                 26                      2
1080                 1                 23                      2
1154                 1                 27                      2
1184                 1                 36                      6
1194                 3                 29                      2
1275                 0                 15                      2
1330                 0                 21                      2
1351                 1                 24                      3
1374                 1                 29                      2

     WorkLifeBalance  YearsAtCompany YearsInCurrentRole  \
18                 3              25                  8
25                 2              14                 13
29                 2               2                  2
65                 3               5                  0
105                3               3                  2
112                3               5                  3
116                3              11                 10
165                3               5                  4
186                3              20                  8
215                3               1                  0
233                2               7                  0
235                3              17                 13
263                2               7                  7
276                2               7                  7
313                3              10                  6
352                1               0                  0
379                3               5                  4
408                1               5                  2
411                1              29                  8
417                3              20                 15
445                3              10                  9
466                3              18                 16
492                1               3                  2
592                2              26                 14
616                2              20                  6
749                3              32                 14
755                4               9                  3
851                3               5                  2
858                3               7                  7
861                3              26                 15
867                3               2                  2
913                3              24                 10
916                3              11                  4
936                3               0                  0
937                3              19                  9
948                3               9                  1
955                3              19                  9
999                3              20                  7
1076               3              14                  9
1080               4              13                 12
1154               3               5                  2
1184               3              10                  8
1194               3               3                  2
1275               3               2                  2
1330               3              16                 12
1351               3              22                 17
1374               2               1                  0

      YearsSinceLastPromotion  YearsWithCurrManager
18                          3                     7
25                          4                     8
29                          2                     1
65                          0                     2
105                         2                     2
112                         4                     4
116                         5                     8
165                         4                     4
186                         9                     9
215                         0                     0
233                         0                     6
235                         1                     9
263                         7                     7
276                         6                     2
313                         8                     8
352                         0                     0
379                         1                     2
408                         1                     4
411                        11                    10
417                         1                    12
445                         7                     7
466                        11                     8
492                         0                     2
592                         3                     0
616                         4                    17
749                         6                     9
755                         1                     1
851                         4                     2
858                         4                     7
861                        15                     9
867                         2                     2
913                         1                    11
916                         0                     8
936                         0                     0
937                        15                     2
948                         0                     8
955                         9                    11
999                         0                     9
1076                        1                    12
1080                        5                     1
1154                        1                     0
1184                        4                     7
1194                        1                     2
1275                        2                     2
1330                        6                    14
1351                        4                     7
1374                        0                     0

[47 rows x 35 columns]

In [31]:
rnd_overtime = df[
    (df["Department"] == "Research & Development") &
    (df["OverTime"] == "Yes")
]

print(rnd_overtime)

      Age Attrition     BusinessTravel  DailyRate              Department  \
2      37       Yes      Travel_Rarely       1373  Research & Development
3      33        No  Travel_Frequently       1392  Research & Development
6      59        No      Travel_Rarely       1324  Research & Development
11     29        No      Travel_Rarely        153  Research & Development
14     28       Yes      Travel_Rarely        103  Research & Development
...   ...       ...                ...        ...                     ...
1435   44        No      Travel_Rarely       1037  Research & Development
1442   29       Yes      Travel_Rarely       1092  Research & Development
1456   35        No  Travel_Frequently       1199  Research & Development
1459   29        No      Travel_Rarely       1378  Research & Development
1467   27        No      Travel_Rarely        155  Research & Development

      DistanceFromHome  Education EducationField  EmployeeCount  \
2                    2          2          Other              1
3                    3          4  Life Sciences              1
6                    3          3        Medical              1
11                  15          2  Life Sciences              1
14                  24          3  Life Sciences              1
...                ...        ...            ...            ...
1435                 1          3        Medical              1
1442                 1          4        Medical              1
1456                18          4  Life Sciences              1
1459                13          2          Other              1
1467                 4          3  Life Sciences              1

      EmployeeNumber  ...  RelationshipSatisfaction StandardHours  \
2                  4  ...                         2            80
3                  5  ...                         3            80
6                 10  ...                         1            80
11                15  ...                         4            80
14                19  ...                         2            80
...              ...  ...                       ...           ...
1435            2020  ...                         3            80
1442            2027  ...                         2            80
1456            2049  ...                         4            80
1459            2053  ...                         1            80
1467            2064  ...                         2            80

      StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
2                    0                  7                      3
3                    0                  8                      3
6                    3                 12                      3
11                   0                 10                      3
14                   0                  6                      4
...                ...                ...                    ...
1435                 0                  6                      2
1442                 3                  4                      3
1456                 2                 10                      2
1459                 1                 10                      2
1467                 1                  6                      0

     WorkLifeBalance  YearsAtCompany YearsInCurrentRole  \
2                  3               0                  0
3                  3               8                  7
6                  2               1                  0
11                 3               9                  5
14                 3               4                  2
...              ...             ...                ...
1435               3               4                  3
1442               4               2                  2
1456               4              10                  2
1459               3               4                  3
1467               3               6                  2

      YearsSinceLastPromotion  YearsWithCurrManager
2                           0                     0
3                           3                     0
6                           0                     0
11                          0                     8
14                          0                     3
...                       ...                   ...
1435                        1                     2
1442                        2                     2
1456                        0                     2
1459                        0                     3
1467                        0                     3

[271 rows x 35 columns]

In [32]:
df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

# task 6

In [35]:
result=df.groupby("Department")["MonthlyIncome"].mean()
print(result)

Department
Human Resources           6654.507937
Research & Development    6281.252862
Sales                     6959.172646
Name: MonthlyIncome, dtype: float64

In [37]:
work=df.groupby('Department')['Age'].mean()
print(work)

Department
Human Resources           37.809524
Research & Development    37.042664
Sales                     36.542601
Name: Age, dtype: float64

In [38]:
income=df.groupby('JobRole')['MonthlyIncome'].mean()
print(income)

JobRole
Healthcare Representative     7528.763359
Human Resources               4235.750000
Laboratory Technician         3237.169884
Manager                      17181.676471
Manufacturing Director        7295.137931
Research Director            16033.550000
Research Scientist            3239.972603
Sales Executive               6924.279141
Sales Representative          2626.000000
Name: MonthlyIncome, dtype: float64

In [39]:
edu=df.groupby("EducationField")["MonthlyIncome"].mean()
print(edu)

EducationField
Human Resources     7241.148148
Life Sciences       6463.288779
Marketing           7348.584906
Medical             6510.036638
Other               6071.548780
Technical Degree    5758.303030
Name: MonthlyIncome, dtype: float64

In [42]:
att=df.groupby("Department")["Attrition"].count()
print(att)

Department
Human Resources            63
Research & Development    961
Sales                     446
Name: Attrition, dtype: int64

In [43]:
YearsAtCompany=df.groupby("Department")["YearsAtCompany"].mean()
print(YearsAtCompany)

Department
Human Resources           7.238095
Research & Development    6.864724
Sales                     7.284753
Name: YearsAtCompany, dtype: float64

In [44]:
result = df.groupby("Department")["EmployeeNumber"].count()

print(result)

Department
Human Resources            63
Research & Development    961
Sales                     446
Name: EmployeeNumber, dtype: int64

In [45]:
result = df.groupby("Department")["MonthlyIncome"].max()

print(result)

Department
Human Resources           19717
Research & Development    19999
Sales                     19847
Name: MonthlyIncome, dtype: int64

In [46]:
result = df.groupby("Department")["MonthlyIncome"].min()

print(result)

Department
Human Resources           1555
Research & Development    1009
Sales                     1052
Name: MonthlyIncome, dtype: int64

In [47]:
result = df.groupby("Department")["MonthlyIncome"].mean()

print(result)

print("\nTop Earning Department:")
print(result.idxmax())

Department
Human Resources           6654.507937
Research & Development    6281.252862
Sales                     6959.172646
Name: MonthlyIncome, dtype: float64

Top Earning Department:
Sales